use std::hash::Hash;

use chiquito::{
    ccs::{
        backend::ccs::{chiquito2CCS, ChiquitoCCSCircuit},
        compiler::{
            cell_manager::SingleRowCellManager,
            compile, // input for constructing the compiler
            config,
            step_selector::SimpleStepSelectorBuilder,
        },
        ir::{assignments::AssignmentGenerator, circuit::Circuit},
    },
    field::Field,
    frontend::dsl::circuit,
    poly::ToField,
    sbpir::SBPIR,
};

// the main circuit function: returns the compiled IR of a Chiquito circuit
// Generic types F, (), (u64, 64) stand for:
// 1. type that implements a field trait
// 2. empty trace arguments, i.e. (), because there are no external inputs to the Chiquito circuit
// 3. two witness generation arguments both of u64 type, i.e. (u64, u64)

type FiboReturn<F> = (Circuit<F>, Option<AssignmentGenerator<F, ()>>, SBPIR<F, ()>);

fn fibo_circuit_ccs<F: Field + From<u64> + Hash>() -> FiboReturn<F> {
    // PLONKish table for the Fibonacci circuit:
    // | a | b | c |
    // | 1 | 1 | 2 |
    // | 1 | 2 | 3 |
    // | 2 | 3 | 5 |
    // | 3 | 5 | 8 |
    // ...

    use chiquito::frontend::dsl::cb::*; // functions for constraint building

    let fibo = circuit::<F, (), _>("fibonacci", |ctx| {
        // the following objects (forward signals, steptypes) are defined on the circuit-level

        // forward signals can have constraints across different steps
        let a = ctx.forward("a");
        let b = ctx.forward("b");

        // define step type
        let fibo_step = ctx.step_type_def("fibo step", |ctx| {
            // the following objects (constraints, transition constraints, witness generation
            // function) are defined on the step type-level

            // internal signals can only have constraints within the same step
            let c = ctx.internal("c");

            // in setup we define the constraints of the step
            ctx.setup(move |ctx| {
                // regular constraints are for signals without rotation only

                // `auto_eq` creates a constraint and also auto generates the witness of the left
                // side.
                ctx.auto_eq(c, a + b);

                // transition constraints accepts forward signals as well
                // constrain that b is equal to the next instance of a by calling `eq` function from
                // constraint builder and `next` on forward signal
                ctx.transition(eq(b, a.next()));
                // constrain that c is equal to the next instance of c, by calling `next` on forward
                // signal
                ctx.transition(eq(c, b.next()));
            });

            // witness generation (wg) function is Turing complete and allows arbitrary user defined
            // logics for assigning witness values wg function is defined here but no
            // witness value is assigned yet
            ctx.wg(move |ctx, (a_value, b_value): (u32, u32)| {
                // println!("fib line wg: {} {} {}", a_value, b_value, a_value + b_value);
                // assign arbitrary input values from witness generation function to witnesses
                ctx.assign(a, a_value.field());
                ctx.assign(b, b_value.field());

                // c is auto generated by `auto_eq`
            })
        });

        ctx.pragma_num_steps(16);

        // trace function is responsible for adding step instantiations defined in step_type_def
        // function above trace function is Turing complete and allows arbitrary user
        // defined logics for assigning witness values
        ctx.trace(move |ctx: _, _| {
            // add function adds a step instantiation to the main circuit and calls witness
            // generation function defined in step_type_def input values for witness
            // generation function are (1, 1) in this step instance
            ctx.add(&fibo_step, (1, 1));
            let mut a = 1;
            let mut b = 2;

            for _i in 1..16 {
                ctx.add(&fibo_step, (a, b));

                let prev_a = a;
                a = b;
                b += prev_a;
            }
        })
    });

    let compiled = compile(
        config(SingleRowCellManager {}, SimpleStepSelectorBuilder {}),
        &fibo,
    );

    (compiled.0, compiled.1, fibo)
}

// After compiling Chiquito AST to an IR, it is further parsed by a Chiquito Halo2 backend and
// integrated into a Halo2 circuit, which is done by the boilerplate code below.

use ark_bn254::Fr as FFr;
use ark_std::log2;
use folding_schemes::{ccs::CCS, utils::vec::dense_matrix_to_sparse};
use halo2_proofs::halo2curves::{bn256::Fr, ff::PrimeField};
fn main() {
    let (chiquito, wit_gen, _) = fibo_circuit_ccs::<Fr>();
    let compiled = chiquito2CCS(chiquito);

    let (witness, steps) = wit_gen.map(|g| g.generate(())).unzip();
    let circuit = ChiquitoCCSCircuit::new(compiled, witness, steps);

    let (ccs, z) = circuit.configure();
    let result = ccs.is_satisfied(&z);
    println!("fibonacci {:#?}", result);

    let (chiquito, wit_gen, _) = fibo_circuit_ccs::<Fr>();
    let compiled = chiquito2CCS(chiquito);
    let (witness, steps) = wit_gen.map(|g| g.generate(())).unzip();
    let circuit = ChiquitoCCSCircuit::new(compiled, witness, steps);
    let (circuit, z) = circuit.configure();

    let ccs = CCS {
        m: circuit.m,
        n: circuit.n,
        l: circuit.l,
        t: circuit.t,
        q: circuit.q,
        d: circuit.d,
        s: log2(circuit.m) as usize,
        s_prime: log2(circuit.n) as usize,
        M: circuit
            .matrics
            .iter()
            .map(|matrix| {
                let values = matrix
                    .values()
                    .iter()
                    .map(|m| {
                        m.iter()
                            .map(|r| {
                                // todo()
                                if Fr::ONE.neg().eq(r) {
                                    FFr::from(-1)
                                } else {
                                    let mut array = [0u8; 8];
                                    array.copy_from_slice(&r.to_repr().as_ref()[0..8]);
                                    FFr::from(u64::from_le_bytes(array))
                                }
                            })
                            .collect()
                    })
                    .collect();
                dense_matrix_to_sparse(values)
            })
            .collect(),
        S: circuit
            .selectors
            .iter()
            .map(|selectors| selectors.iter().map(|(idx, _)| *idx).collect())
            .collect(),
        c: (0..circuit.q).map(|_| FFr::from(1)).collect(),
    };

    let assignments = z
        .assignments
        .iter()
        .map(|r| {
            if Fr::ONE.neg().eq(r) {
                FFr::from(-1)
            } else {
                let mut array = [0u8; 8];
                array.copy_from_slice(&r.to_repr().as_ref()[0..8]);
                FFr::from(u64::from_le_bytes(array))
            }
        })
        .collect();
    let public_inputs = z
        .public_inputs
        .iter()
        .map(|r| {
            if Fr::ONE.neg().eq(r) {
                FFr::from(-1)
            } else {
                let mut array = [0u8; 8];
                array.copy_from_slice(&r.to_repr().as_ref()[0..8]);
                FFr::from(u64::from_le_bytes(array))
            }
        })
        .collect();
    let inputs = [vec![FFr::from(1)], assignments, public_inputs].concat();

    let result = ccs.check_relation(&inputs);
    println!("sonobe fibonacci = {:?}", result);
}
